[server]
port = "3000"

[database]
enabled = false
host = "localhost"
port = 5432
db-name = "mydb?sslmode=disable"
user = "postgres"
password = "qwerty"
pool-size = 1
log-queries = false

[iam]
base-url = "http://localhost:3000"

# Check Makefile generate-hmac-key command to generate this key
hmac-secret = ""

[email]
enabled = false
from = ""
api-key = ""
otp-template = ""
invite-template = ""
