version: "2"

run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocritic
    - gocognit
    - gosec
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - goimports
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  